spring.application.name=votrebanque


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Instructs Spring Boot to wait until Hibernate has created the tables before executing import.sql
spring.jpa.defer-datasource-initialization=true

# Ensures that SQL initialization is properly enabled (sometimes restricted by default)
spring.sql.init.mode=always

# Instruct Spring Boot to execute YOUR 'import.sql' file.
spring.sql.init.data-locations=classpath:import.sql


# Maximum time a connection can remain inactive in the pool (e.g., 10 minutes)
spring.datasource.hikari.idle-timeout=600000

# Maximum lifespan of a connection in the pool (e.g., 30 minutes)
spring.datasource.hikari.max-lifetime=1800000

# The "Keep-Alive" feature: Hikari will send an invisible "ping" every x milliseconds
# to tell PostgreSQL "Hey, I'm still here, don't close the line!".
spring.datasource.hikari.keepalive-time=30000

# Maximum time Spring will wait to establish a connection before throwing an error (e.g., 15 seconds)
spring.datasource.hikari.connection-timeout=15000


#Instructs Testcontainers to start a PostgreSQL Docker container when the application launches.
spring.datasource.url=jdbc:tc:postgresql:16-alpine:///votrebanque
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver

#url frontend
app.frontend.base-url=http://localhost:4200

# CONFIGURATION POUR LE DEV LOCAL (avec Mailpit)
app.mailpit.api-url=http://localhost:8025
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# --- OU ---

# CONFIGURATION POUR LA PROD (Exemple Brevo / Sendinblue)
# spring.mail.host=smtp-relay.brevo.com
# spring.mail.port=587
# spring.mail.username=votre-adresse-brevo@email.com
# spring.mail.password=votre-cle-api-smtp
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true


#token
app.jwt.secret=${JWT_SECRET}
app.jwt.validity-ms=1800000