spring.datasource.url=jdbc:postgresql://postgres:5432/votrebanque
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USER:votrebanque}
spring.datasource.password=${POSTGRES_PASSWORD:votrebanque}

spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

app.frontend.base-url=${FRONTEND_BASE_URL:http://localhost:4200}
